### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by MarkTrinder** [dmpstats/stochCRM#10]
Hi

I am using my own random density data, saved using the template. Leaving all the other inputs on their defaults and just selecting the density file (which apparently uploads correctly as the histograms are all present and look fine), when I run the simulation I get this error to the console:

Warning: Error in : `by` can't contain join column `specLabel` which is missing from LHS
  82: <Anonymous>

**Comment by bcaneco** [comment]
Hi Mark,
Issue should be fixed now. 

Thanks for once again helping us debugging the code, it's really appreciated. 
Regards
