### ISSUE TITLE
SD for nocturnal activity factors

### ISSUE THREAD

**Issue by jb1103** [dmpstats/stochCRM#14]
Hi All

I'm wondering what values people have used so far for nocturnal activity, and specifically for the SD? current advice is based on categories which have usually been assigned a range of activity values, e.g. between 25% and 50% for kittiwake and large gulls. How can this be input into the stochastic model and how can a standard deviation be generated? So I'd presume that a mid-point might be appropriate as the mean, but how to estimate what an appropriate SD might be? NOTE that I am aware there is now empirical evidence for some species, and we expect there to be more of this, across more species, available soon. But in the meantime for some species these categories/ranges are all that is currently available. 

Thanks in advance. 

Julie

**Comment by alexrobbins1** [comment]
I'm attempting to run some models and have been trying to work out what SD to use for values that have been presented without them. No advice with regard to nocturnal activity but agree its an issue for multiple parameters that needs to be resolved!

**Comment by statsgeeknz** [comment]
Hi all.
A question beyond the app developers competencies I fear. I'll raise with relevant parties and get them involved in the conversation.

Regards
C

**Comment by thomasevans** [comment]
Hi Carl, Julie, Alex,
I agree with Carl that this is beyond the app developers
competence/responsibility. I would be happy to have a call with Alex and
Julie later this week (or when convenient) to discuss this and any other
issues identified in running the tool.
Thanks,
Tom
