### ISSUE TITLE
Disconnected from server on simulation runs

### ISSUE THREAD

**Issue by grwhumphries** [dmpstats/stochCRM#2]
Getting a 'disconnected from server' error when simulations are run.

**Comment by bcaneco** [comment]
Hi Grant. Are you allowing the app to populate all the fields in each species-specific tab before hitting the simulation button? If you jump straight to the simulation tab before the species features are defined (i.e. activating their panels), it will crash. 

There is a  shiny option to populate all fields automatically at launching (as opposed to only when the panel is viewed, as it is currently), but that will probably result in an even slower rendering at launch. 

Cheers

**Comment by grwhumphries** [comment]
Aye - I am, but a potential solution might be to not allow access to the simulation tab until after the species features are defined. Or grey out the selection functions in the simulation tab until conditions are met - otherwise, set a warning message.

**Comment by bcaneco** [comment]
So, is it still crashing if you go through the species tabs before starting the simulation?

Thanks for the suggestions - a warning device of that sort was already under consideration for the next coding iteration.
