### ISSUE TITLE
Kittiwake default flight speed (possibly other parameters too?)

### ISSUE THREAD

**Issue by thomasevans** [dmpstats/stochCRM#27]
Black legged-kittiwake are set as the default species for the sCRM. When running the sCRM for other species the default species parameter information is taken from the global defaults: https://github.com/dmpstats/stochCRM/blob/2855bc35da6e31fa4856a28e5b5e5765c0fff39d/data/default%20species%20dimensions%20and%20flightspeeds.csv
However, when using black-legged kittiwake these defaults are overwritten by hard-coded parameter values:
https://github.com/dmpstats/stochCRM/blob/2855bc35da6e31fa4856a28e5b5e5765c0fff39d/global.r#L92
Please could you change the code so that the kittiwake parameter values are populated from the global defaults instead.
This is definitely an issue for flight speed, it may also be an issue for other parameter values which are also currently hard-coded for kittiwake.
Thanks, Tom

**Comment by thomasevans** [comment]
Just looking at this further now I think all that is needed is to edit line 88 https://github.com/dmpstats/stochCRM/blob/2855bc35da6e31fa4856a28e5b5e5765c0fff39d/global.r#L88

From:
`Black_legged_Kittiwake = list(
      meanDensity = c(0.97, 1.04, 1.15, 0.48, 0.56, 0.63, 0.68, 0.64, 0.53, 1.20, 1.02, 0.99),
      sdDensity = c(0.67, 0.75, 0.78, 0.36, 0.58, 0.45, 0.47, 0.47, 0.39, 0.78, 0.61, 0.7),
      trucDensity = c(0,2), bodyLt_E = 0.39, bodyLt_SD = 0.005, wngSpan_E = 1.08, wngSpan_SD = 0.04,
      flSpeed_E = 7.26,  flSpeed_SD = 1.5, noctAct_E = 0.033, noctAct_SD = 0.0045, CRHeight_E = 0.06,
      CRHeight_SD = 0.009, basicAvoid_E = 0.989, basicAvoid_SD = 0.001, extAvoid_E = 0.967, extAvoid_SD = 0.002,
      flType = "Flapping"
    )`
    
To:
`Black_legged_Kittiwake = dfltSpecSizeAndSpeed$Black_legged_Kittiwake,
`

**Comment by grwhumphries** [comment]
Heya Tom, 

Do you need this done ASAP? Or is it something that could wait for a little longer?  Bruno should soon be updating the sCRM in the very very near future to the latest version anyways with a lot of changes to the tools and code - including integration of the stochLAB functions from the new CRM library.

**Comment by bcaneco** [comment]
Hi Grant, 

I was in touch with Tom via email and we agreed I'd implement a quick patch to fix the issues in the coming days. Yes, the new update will be coming soon (fingers crossed), which will address this issue anyway, but my understanding is that  there is some urgency in having this fixed. 

It shouldn't take long to patch it. It'll be along the lines of what Tom is proposing above - but for a couple of parameter only as there are no agreed defaults for other parameters like e.g. densities.

Thanks for checking on this anyway.

**Comment by thomasevans** [comment]
Hi Grant and Bruno,

This was raised earlier this week by Natural England. It was raised last year too but was not fixed at that time (though I don't think a GitHub issue was raised - only a traditional email!) The new version of the tool being developed for the MS project should soon supersede this, but that will need to be finalised and signed-off on etc, so it is important to have this fixed for existing version in the interim. So yes, I'd appreciate if this can be done ASAP.

Thanks,
Tom

**Comment by bcaneco** [comment]
Hi Tom, Grant

I've just pushed a few changes to the source code. Default values for body length, wingspan and flight speed for Kittiwake are now fetched from the global file. Note, no data available for SD of flight speed, so that is still a non-data based default. 

A few other changes were required to deploy the app, as one of the dependencies ({d3heatmap}) is not available from CRAN anymore. Thus, one of the charts used to visualize FHDs has been removed. 

I've tested the updated app and it seems to be working as expected. But, to be on the side of caution, specially if stochCRM is currently on high demand, I've deployed a test version on a temporary site for you guys to have a quick spin, if you wish so. 

https://dmpstats.shinyapps.io/shiny-stochCRM_test

All going well, I'll deploy the app on the official address at some point next week.

Cheers

**Comment by thomasevans** [comment]
Hi Bruno,

Many thanks for making these changes. I had a quick look at the test version - it looks ok to me, though I haven't done a detailed test.

This change was primarily requested by Tim F at Natural England. I have emailed Tim together with others copied in to an earlier email thread to request that they come back with any comments by close next Wednesday (21/03/2022), assuming no comments then this can be deployed to replace the main published version. I cc'ed you into that email for awareness of any replies (NB I'm away the next two weeks but hopefully you won't need my input).

Thanks,
Tom

**Comment by thomasevans** [comment]
Hi @bcaneco 

Just to let you know I did not receive any additional comments on the test version you put out. Therefore please could you go ahead and deploy this version to the Shiny Server.

Thanks,
Tom

**Comment by bcaneco** [comment]
Hi @thomasevans,

I've just deployed the updated version of the app onto the shinyapp.io server, so it should be available on the official website. 

I'll close this issue for the time being, but feel free to re-open it if anything else comes up regarding this topic.
