### ISSUE TITLE
crosstalk

### ISSUE THREAD

**Issue by MarkTrinder** [dmpstats/stochCRM#4]

**Comment by MarkTrinder** [comment]
sorry - posted with no content!

I think this package may have been omitted from the install list - I had an error flag that this was missing, but I'm not sure how I triggered it. Installed it manually and the script ran fine.

**Comment by bcaneco** [comment]
That's interesting, if not a bit weird.  Packages with dependencies should automatically install required packages, in this case crosstalk.  

Not sure which of the main used packages depends on crosstalk, but we will have a look.

Thanks

**Comment by MarkTrinder** [comment]
I can’t remember exactly how I triggered that one. And because I installed it manually it obviously didn’t happen again.
I’m doing my best to break it though.
