### ISSUE TITLE
windspeed

### ISSUE THREAD

**Issue by Pete-Nelson** [dmpstats/stochCRM#5]
Any plans to incorporate windspeed in the model? Or perhaps I missed it!

**Comment by bcaneco** [comment]
Hi Pete,

Rotor speed and pitch vs. windspeed relationships are available as model inputs in the "Rotation Speed and Blade Pitch" section of the "Turbine Parameters" box. 

Just select the "Wind speed relationship" button and the inputs (two tables and two input fields) should appear bellow it. Sometimes the tables are bit shy and don't show up when the option is selected for the first time (rendering tantrums... common in these types of input tables).  But if you click in the area bellow the buttons, or switch to "probability distributions" and back to "Wind speed relationship", the tables will pop up. It's a bit of a nuisance, but these editable tables are extremely convenient for inputting tabular data. 

Thanks for getting in touch.
