### ISSUE TITLE
summing of months - median

### ISSUE THREAD

**Issue by MarkTrinder** [dmpstats/stochCRM#7]
the summary table for each model option is not summing the monthly medians correctly:

![image](https://user-images.githubusercontent.com/26790029/49504966-a865bc80-f872-11e8-80f5-be1e01aa79a5.png)

annual median = 269.99

![image](https://user-images.githubusercontent.com/26790029/49504993-b4ea1500-f872-11e8-9c03-a7d5682b6920.png)

sum of monthly medians = 169.56

**Comment by bcaneco** [comment]
Hi Mark, 
The median of the sums is not necessarily equal to the sum of the medians. Specially when the distributions are heavily skewed like the monthly distributions you are getting in the model outputs. 

The annual distribution of collisions is obtained by summing over simulated monthly estimates drawn at each iteration step. In this way, the error/uncertainty associated with each month estimate is properly combined and propagated into the annual distribution. 

If the distributions of monthly estimates have a heavy right tail, the monthly medians do not carry info on those large tail values, and therefore the sum of the medians will fall bellow the median of the annual distribution. 

If the distribution of monthly estimates are approximately symmetric, then the median approximates the mean, therefore taking the linear properties of the mean, i.e.: median(sums) ≈ mean(sums) = sum(means) ≈ sum(medians). 

Hopes this makes sense.

Thanks for the feedback!
