### ISSUE TITLE
gannet height data

### ISSUE THREAD

**Issue by MarkTrinder** [dmpstats/stochCRM#8]
the gannet flight height distribution data (Northern_Gannet_ht.csv) contains the same data repeated in each column rather than a randomised sample.

**Comment by bcaneco** [comment]
Hi Mark,
The original FHD data file for gannets seems to have been overwritten at some point during the app development. I've uploaded all the original FHD datasets available from the Masden model, so Gannets should now have a random sample of FHD. 

Thanks again for your feedback.

**Comment by MarkTrinder** [comment]
OK.  But I think that may be the same as kittiwake: after I sent this I looked at the Masden gannet data and found it was the same as the kittiwake one.


Sent from my phone

-------- Original message --------
From: bcaneco
Date:28/01/2019 11:28 (GMT+00:00)
To: dmpstats/stochCRM
Cc: Mark Trinder , Author
Subject: Re: [dmpstats/stochCRM] gannet height data (#8)


Hi Mark,
The original FHD data file for gannets seems to have been overwritten at some point during the app development. I've uploaded all the original FHD datasets available from the Masden model, so Gannets should now have a random sample of FHD.

Thanks again for your feedback.

**Comment by bcaneco** [comment]
That is strange - the data for kittiwakes appeared correct before the last data reload. Did you also get repeated data showing in the app's FHD plots?

All default species got their original FHD data sets reloaded this morning. I've just downloaded the app files from GitHub and checked the FHD files for a few species (inc. gannets and kittiwakes) and they all contain random samples of FHD. I also ran the app and, at least for the species checked, the FHD plots also show randomized sets of distributions.

For info, the names of the FHD data files in the app's "/data/" folder have changed slightly, for programming reasons, now ending with "xx_ht_dflt.csv".

Cheers.

**Comment by MarkTrinder** [comment]
Sounds like the problem is resolved – perhaps I have a draft version of the Masden data which included this error. It was only by chance that I happened to compare the data for gannet and kittiwake and saw they were identical.
Thanks for checking it out.

**Comment by MarkTrinder** [comment]
hi

the gannet and kittiwake flight heights in these files are still identical: 
Black_legged_Kittiwake_ht_dflt.csv
Northern_Gannet_ht_dflt.csv

could you check this please?

**Comment by bcaneco** [comment]
Hi, 

I've checked the original FHD data source provided to us (also available [here](http://data.marine.gov.scot/dataset/developing-avian-collision-risk-model-incorporate-variability-and-uncertainty-r-code)) and the FHD for gannets and kittiwakes are also identical . Checked the original Johnston's JAE paper, but no data is being provided there. 

I guess the question is whether the data is deliberately identical (e.g. maybe random FHD for gannets not being available, kittiwake's is the best next thing?) or if there is an error. If it's an error at source, I'm afraid we won't be able to fix it as I believe it would be beyond the remit of the work originally commissioned to us.

Regards

**Comment by MarkTrinder** [comment]
Hi

Earlier this week I contacted BTO (Aonghais Cook, one of the co-authors on the original source publication) and was sent the ‘definitive’ dataset for this (the bootstrap resamples) and this has identical data to that bundled with the sCRM, except for gannet for which (I assume) the right data were included. I suggest you contact BTO and request this too to update your data.

**Comment by bcaneco** [comment]
Would it be at all possible to send us a copy of that "definite" dataset version, please? Or do we need to go through the formal route and place an official request to BTO to provide us the correct data?

Thanks

**Comment by bcaneco** [comment]
FHD data updated with the bootstrap resamples from the original source publication (Johnson et al, 2014), kindly provided by Aonghais Cook. 

Special thanks to Mark Trinder for facilitating access to the source data.
