### ISSUE TITLE
donwloadable app: no 'pacman' package

### ISSUE THREAD

**Issue by jb1103** [dmpstats/stochCRM#9]
Hi, having had the 'disconnected from server' error several times (including when I follow the advice on a previous thread about that), I decided to instead download a local copy. However, when I then try to run the app within the global.r, it cannot load because there is no package called pacman. My understanding of this was that I do not need to have R or indeed any specific packages installed on my machine, so I am not sure what to do with this error. Any suggestions? I have checked whether there is something in the downloaded files called pacman, and there is not. Should there be? 

thanks

**Comment by bcaneco** [comment]
Hi, we're sorry you are experiencing connection problems with the app. The server hosting the app has shown to be extremely unstable in certain hours of the day. It's an issue we would like to address in a near future.

To use the local version you will need to have [R](https://cran.r-project.org/) installed on your machine. Then, if [RStudio Desktop](https://www.rstudio.com/products/rstudio/download/) is already installed, all you need to do is run the global.r file as described in the app's "How to Run" section - the app itself should take care of installing all the required packages, including `pacman`.

Hope this helps.

**Comment by jb1103** [comment]
Thanks for the prompt and helpful reply. 

I suspect the problem is that the R version installed on my machine is quite old. 

However note that in the instructions (both online, and in the 'read me' that is downloaded along with all the other files for the local machine version) it states that 'Users are not required to install or maintain R'. This is a bit misleading.

**Comment by bcaneco** [comment]
Hi,
Point taken regarding the instructions being misleading - text has been, hopefully, suitably amended.

Thanks for the feedback.
